config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  
  resources :blogs do
  	member do
  		get :toggle_status
  	end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'

end

app/models/blog.rb
class Blog < ApplicationRecord
	enum status: { draft: 0, published: 1 }
	extend FriendlyId
	friendly_id :title, use: :slugged

	validates_presence_of :title, :body, :topic_id

	belongs_to :topic

	has_many :comments, dependent: :destroy

	def self.special_blogs
		all
	end

	def self.featured_blogs
		limit(2)
	end

	def self.recent
		order("created_at DESC")
	end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy toggle_status]
  before_action :set_sidebar_topics, except: [:update, :create, :destroy, :toggle_status]

  layout "blog"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all

  # GET /blogs or /blogs.json
  def index
    # @blogs = Blog.special_blogs

    if logged_in?(:site_admin)
      @blogs = Blog.recent.page(params[:page]).per(5)
    else
      @blogs = Blog.published.recent.page(params[:page]).per(5)
    end
    @page_title = "My Portfolio Blog"
    @show_masterHead = true;
  end

  # GET /blogs/1 or /blogs/1.json
  def show
    if logged_in?(:site_admin) || @blog.published?
      @blog = Blog.includes(:comments).friendly.find(params[:id])
      @comment = Comment.new

      @page_title = @blog.title
      @seo_keywords = @blog.body
    else
      redirect_to blogs_path, notice: "You are not authorized to access this page"
    end

  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @blog.topic_id = Topic.first.id;
    
    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: "Blog was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def toggle_status
    # byebug
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end
      
    redirect_to blogs_url, notice: 'Post status has been updated.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body, :topic_id, :status)
    end

    def set_sidebar_topics
      @side_bar_topics = Topic.with_blogs
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
	def gravatar_helper user
		image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 60
	end


	class CodeRayify < Redcarpet::Render::HTML
		def block_code(code, language)
			CodeRay.scan(code, language).div
		end
	end

	def markdown(text)
		coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)

		options = {
			fenced_code_blocks: true,
			no_intra_emphasis: true,
			autolink: true,
			lax_html_blocks: true
		}

		markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
		markdown_to_html.render(text).html_safe
	end

	def blog_status_color blog
		'color: red;' if blog.draft?
	end
end

app/views/blogs/_admin_actions.html.erb
<% if logged_in?(:site_admin) %>
   <nav aria-label="breadcrumb">
	    <ol class="breadcrumb blogcrumb">
	      <li class="breadcrumb-item">
	        <%= link_to fa_icon('file-text'), toggle_status_blog_path(blog), style: blog_status_color(blog) %> 
	      </li>
	      <li class="breadcrumb-item">
	        <%= link_to fa_icon('pencil-square'), edit_blog_path(blog) %>
	      </li>
	      <li class="breadcrumb-item" aria-current="page">
	        <%= link_to fa_icon('trash'), blog, method: :delete, data: { confirm: 'Are you sure?' } %>
	      </li>
	    </ol>
  </nav>
<% end %>

app/views/blogs/_blog.html.erb
<div class="blog-post">
    <h2 class="blog-post-title"><%= link_to blog.title.upcase, blog %></h2>
    <p class="blog-post-meta">
    	<%= distance_of_time_in_words(blog.created_at, Time.now) %> ago by <a href="#">Kevin Mark Montesclaros</a> <br>

    	 <%= render partial: 'blogs/admin_actions', locals: {blog: blog} %>
    </p>

    <p><%= blog.body %></p>
</div><!-- /.blog-post -->

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <% blog.errors.full_messages.each do |error| %>
        <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= form.text_field :title, class: 'form-control', placeholder: 'Title' %>
  </div>

  <div class="form-group">
    <%= form.label :topic_id %>
    <%= form.collection_select(
      :topic_id, 
      Topic.all, 
      :id, 
      :title, 
      {
        include_blank: true
      },
      class: 'form-control'
    )%>
  </div>

  <div class="form-group">
    <%= form.radio_button :status, 'draft' %>
    <%= form.label :status, 'Draft' %>

    <%= form.radio_button :status, 'published' %>
    <%= form.label :status, 'Published' %>
  </div>

  <div class="form-group">
    <%= form.text_area :body, class: 'form-control', rows: 10, placeholder: 'Content' %>
  </div>

  <div class="form-group">
    <%= form.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="col-md-8 blog-main">
	<h1>Editing Blog</h1>

	<%= render 'form', blog: @blog %>

	<%= link_to 'Show', @blog %> |
	<%= link_to 'Back', blogs_path %>

</div>

app/views/blogs/index.html.erb
<div class="col-md-8 blog-main">
  <%= render @blogs %>
  <%= paginate @blogs %>
</div>

app/views/blogs/new.html.erb
<div class="col-md-8 blog-main">
	<h1>New Blog</h1>

	<%= render 'form', blog: @blog %>

	<%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/show.html.erb
<div class="col-md-8 blog-main">
  <div class="d-flex justify-content-between mb-2">
    <h3 class="font-italic">
      <%= @blog.title %>
    </h3>
    <% if logged_in?(:site_admin) %>
      <span class="pull-right">
        <%= link_to fa_icon('pencil-square'), edit_blog_path(@blog) %>
        <%= link_to fa_icon('trash'), @blog, method: :delete, data: {confirm: 'Are you sure want to delete'} %>
      </span>
    <% end %>
  </div>



  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <%= link_to "Home", root_path%>
      </li>
      <li class="breadcrumb-item">
        <%= link_to @blog.topic.title, topic_path(@blog.topic) %>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        <%= @blog.title %> 
      </li>
    </ol>
  </nav>

  <p>
	  <%= markdown @blog.body %>
  </p>

	<%= render 'comments/comment_form' %>

	<div id="comments" data-blog-id="<%= @blog.id %>">
	<%= render @blog.comments %>
	</div>
</div>