config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  
  resources :blogs do
  	member do
  		get :toggle_status
  	end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'

end

app/views/shared/_application_footer.html.erb
  <footer class="mastfoot mt-auto">
    <div class="inner">
      <p class="app-footer"><%= copyright_generator %></p>
    </div>
  </footer>

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Kevin Mark Montesclaros</h3>
    <nav class="nav nav-masthead justify-content-center app-nav">
      <%= nav_helper "nav-link", 'span' %>
      <%= login_helper "nav-link" %>
    </nav>
  </div>
</header>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= copyright_generator %>
  </p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
  <div class="jumbotron p-4 p-md-5 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
      <!-- <h1 class="display-4 font-italic">Title of a longer featured blog post</h1> -->
      <h2 class=" font-italic">Alright lets read some crap 😂</h2>
      <p class="lead my-3">No real content for now</p>
      <!-- <p class="lead mb-0"><a href="#" class="text-white font-weight-bold">Continue reading...</a></p> -->
      <p>
      	<%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %>  	
      </p>
<!--       <p>
      	<%= link_to "Topics", topics_path %>
      </p> -->
    </div>
  </div>

app/views/shared/_blog_nav.html.erb
<header class="blog-header bg-light">
  <nav class="navbar navbar-expand-lg navbar-light mb-5 container">
    <%= link_to "Kevin Mark Montesclaros", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= nav_helper "nav-item nav-link", 'a' %>
        <%= login_helper 'nav-item nav-link' %>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_blog_sidebar.html.erb
<aside class="col-md-4 blog-sidebar">
  <div class="p-4 bg-light rounded">
    <h4 class="font-italic">About</h4>
    <p class="mb-0">Saw you downtown singing the Blues. Watch you circle the drain. Why don't you let me stop by? Heavy is the head that <em>wears the crown</em>. Yes, we make angels cry, raining down on earth from up above.</p>
  </div>


  <%= source_helper("alert alert-info p-4 mt-4") %>

<!--   <div class="p-4">
    <h4 class="font-italic">Archives</h4>
    <ol class="list-unstyled mb-0">
      <li><a href="#">March 2014</a></li>
      <li><a href="#">February 2014</a></li>
      <li><a href="#">January 2014</a></li>
      <li><a href="#">December 2013</a></li>
      <li><a href="#">November 2013</a></li>
      <li><a href="#">October 2013</a></li>
      <li><a href="#">September 2013</a></li>
      <li><a href="#">August 2013</a></li>
      <li><a href="#">July 2013</a></li>
      <li><a href="#">June 2013</a></li>
      <li><a href="#">May 2013</a></li>
      <li><a href="#">April 2013</a></li>
    </ol>
  </div> -->

  <div class="p-4">
    <h4 class="font-italic">Topics</h4>
    <ol class="list-unstyled">
      <% @side_bar_topics.each do |topic| %>
        <p><%= link_to topic.title, topic_path(topic) %></p>
      <% end %>
    </ol>
  </div>

  <div class="p-4">
    <h4 class="font-italic">Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://github.com/electricfeel1979" target="_blank"><%= fa_icon "github" %> Github</a></li>
      <li><a href="https://www.linkedin.com/in/kevinmarkmontesclaros/" target="_blank"><%= fa_icon "linkedin" %> LinkedIn</a></li>
      <li><a href="https://www.facebook.com/ywonttheytalktome/" target="_blank"><%= fa_icon "facebook" %> Facebook</a></li>
      <li><a href="https://twitter.com/KevinMark1251" target="_blank"><%= fa_icon "twitter" %> Twitter</a></li>
      <li><a href="https://www.instagram.com/ywonttheytalktome/" target="_blank"><%= fa_icon "instagram" %> Instagram</a></li>
      <li><a href="https://soundcloud.com/kevimm" target="_blank"><%= fa_icon "soundcloud" %> SoundCloud</a></li>
      <li><a href="https://open.spotify.com/user/12184019549?si=j6eKpKZCSAKhQs1D_uf9Hg" target="_blank"><%= fa_icon "spotify" %> Spotify</a></li>
    </ol>
  </div>
</aside><!-- /.blog-sidebar -->

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About Me", about_me_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Blog", blogs_path %></div>
  <div><%= link_to "Portfolio", portfolios_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
	  <%= link_to 'View all Portfolio Items', portfolios_path %> /
      <a href="#">Back to top</a>
    </p>
    <p><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1>My Portfolio</h1>
    <p class="lead text-muted">No real content for now...</p>
    <p>
      <%= link_to 'About Me', about_me_path, class: 'btn btn-primary my-2' %>
      <%= link_to 'My Blog', blogs_path, class: 'btn btn-secondary my-2' %></a>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">Progressive Web and Mobile App Developer</h4>
          <p class="text-muted">
            No real content for now.
          </p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Explore</h4>
          <ul class="list-unstyled">
            <%= nav_helper "text-white", 'li' %>
            <li>
              <%= login_helper 'text-white' %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <%= link_to "Kevin Mark Montesclaros", root_path, class: "navbar-brand d-flex align-items-center font-weight-bold nav-header-title" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>